head: 
   favicon: "/favicon.ico" #  the favicon
   high_res_favicon: "/assets/images/favicon.png" #  the favicon using high quality format
   apple_touch_icon: "/assets/images/favicon.png" # the iOS Home button icon
   keywords: "Town,软件开发,软件破解,软件美化,软件汉化,软件加密,文科,技术宅" #  the site keywords

uiux:
   android_chrome_color: "#1abc9c" #  the color of the Chrome address bar
   nprogress_color: "#29d" #  the color of the top loading progress bar
   nprogress_buffer: 200 # the top loading progress bar buffers
   meng: true # meng

background: 
   purecolor: "#fff" # the background color

img: 
   avatar: "/assets/images/favicon.png" # your avatar

card: 
   card_shadow: 1 # card shadow (0-24), 0 is not displayed
   card_hoverable: true # When the hover to deepen the shadow

many_authors: false

sns_share: # SNS Share Switch
   twitter: true
   facebook: true
   googleplus: false
   weibo: true
   linkedin: true
   qq: true
   telegram: false
  
comment:
  used: "gitment" # disqus,livere,gitment
  # disqus config
  disqus_shortname: "townwang" # Your disqus 
  disqus_button: false # disqus load button
  disqus_proxy: false # # disqus proxy(Do not use)
  disqus_proxy_url: "" # (Do not use)
  disqus_api_key: "" # (Do not use)
  # livere config
  livere_type: 'city'
  livere_data_uid: ''
  #issues
  # gitment config
  owner: "Townwang"
  repo: "Townwang.github.io"
  client_id: "fd8bd0ccbd0dcef92c53"
  client_secret: "52f903d38833a4434295017cc09c2201d711c3b2"
  
prism:
  themes: prism-okaidia 
  components: 
    - bash 
  plugins: 

mathjax: true

google_analytics: ""  # google analytics code

lang: "zh-CN"  # lang

deploy: "coding" # if you used coding pages